// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw7_s34434;

#nullable disable

namespace PJATK_APBD_Cw7_s34434.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519172125_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturesId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturesId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "I9-14900K",
                            ComponentManufacturesId = 1,
                            ComponentTypeId = 1,
                            Name = "Intel Core i9-14900K"
                        },
                        new
                        {
                            Code = "RX7900XTX",
                            ComponentManufacturesId = 2,
                            ComponentTypeId = 2,
                            Name = "AMD Radeon RX 7900 XTX"
                        },
                        new
                        {
                            Code = "DDR5-32GB",
                            ComponentManufacturesId = 2,
                            ComponentTypeId = 3,
                            Name = "DDR5 32GB 6000MHz"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.ComponentManufacture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("FoundationDate")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufactures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "Intel",
                            FoundationDate = new DateTime(1968, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Intel Corporation"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "NVIDIA",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Central Processing Unit"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Processing Unit"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Random Access Memory"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("PCs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Pro",
                            Stock = 10,
                            Warranty = "3 lata",
                            Weight = 8.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "WorkStation X",
                            Stock = 5,
                            Warranty = "2 lata",
                            Weight = 12.0
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Budget Build",
                            Stock = 20,
                            Warranty = "1 rok",
                            Weight = 6.5
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasMaxLength(10)
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents", (string)null);

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "I9-14900K",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RX7900XTX",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 2,
                            ComponentCode = "DDR5-32GB",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "I9-14900K",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "DDR5-32GB",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.Component", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s34434.DTOs.ComponentManufacture", "ComponentManufacture")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s34434.DTOs.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ComponentManufacture");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.PCComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s34434.DTOs.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s34434.DTOs.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.ComponentManufacture", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s34434.DTOs.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
